SELECT G.BOARD_ID, G.WRITER_ID, G.TITLE, G.PRICE, 
CASE 
    WHEN(STATUS = 'SALE') THEN '판매중' 
    WHEN(STATUS = 'RESERVED') THEN '예약중'
    WHEN(STATUS = 'DONE') THEN '거래완료'
END  AS STATUS
FROM USED_GOODS_BOARD G WHERE CREATED_DATE = '2022-10-05'
ORDER BY BOARD_ID DESC
